class ArticleModel {
  final String title;          // 文章标题
  final String summary;        // 文章摘要
  final String coverImage;     // 文章封面图
  final String source;         // 来源
  final String category;       // 类别/领域
  final String date;           // 日期
  final String id;             // 文章ID

  ArticleModel({
    required this.title,
    required this.summary,
    required this.coverImage,
    required this.source,
    required this.category,
    required this.date,
    required this.id,
  });

  // 创建一些模拟数据
  static List<ArticleModel> getMockData() {
    return [
      ArticleModel(
        id: '1',
        title: 'Flutter 3.0 Released: Performance Boost and New Features',
        summary: 'Flutter 3.0 brings significant performance improvements, including faster startup times and smoother animations. The new version also adds complete support for multiple platforms.',
        coverImage: 'https://pic4.zhimg.com/v2-dde84723b58e2d208690c490dc060735_720w.jpg?source=172ae18b',
        source: '技术日报',
        category: '科技',
        date: '2024-01-15',
      ),
      ArticleModel(
        id: '2',
        title: 'AI Applications in Daily Life',
        summary: 'AI technology is changing our lifestyle, from smart homes to autonomous driving, from medical diagnosis to financial services, AI applications are everywhere.',
        coverImage: 'https://pic4.zhimg.com/v2-dde84723b58e2d208690c490dc060735_720w.jpg?source=172ae18b',
        source: '科技前沿',
        category: '科技',
        date: '2024-01-14',
      ),
      ArticleModel(
        id: '3',
        title: 'Blockchain Technology: Applications Beyond Cryptocurrency',
        summary: 'Blockchain technology is not only applied to cryptocurrencies but also shows great potential in supply chain management, digital identity authentication, smart contracts and other fields.',
        coverImage: 'https://pic4.zhimg.com/v2-dde84723b58e2d208690c490dc060735_720w.jpg?source=172ae18b',
        source: '财经周刊',
        category: '财经',
        date: '2024-01-13',
      ),
      ArticleModel(
        id: '4',
        title: 'The Future of Quantum Computing',
        summary: 'Quantum computing is expected to bring revolutionary breakthroughs in cryptography, drug discovery, materials science and other fields, with major tech companies investing heavily in R&D.',
        coverImage: 'https://pic4.zhimg.com/v2-dde84723b58e2d208690c490dc060735_720w.jpg?source=172ae18b',
        source: '科学杂志',
        category: '科技',
        date: '2024-01-12',
      ),
      ArticleModel(
        id: '5',
        title: 'Global Progress in 5G Network Deployment',
        summary: '5G networks are accelerating deployment worldwide, providing strong network support for IoT, autonomous driving, telemedicine and other applications.',
        coverImage: 'https://pic4.zhimg.com/v2-dde84723b58e2d208690c490dc060735_720w.jpg?source=172ae18b',
        source: '通信世界',
        category: '科技',
        date: '2024-01-11',
      ),
      ArticleModel(
        id: '6',
        title: 'Metaverse: New Boundaries Between Virtual and Reality',
        summary: 'The rise of the metaverse concept marks a new stage in internet development, with virtual and augmented reality technologies reshaping our social and work methods.',
        coverImage: 'https://pic4.zhimg.com/v2-dde84723b58e2d208690c490dc060735_720w.jpg?source=172ae18b',
        source: '数字时代',
        category: '科技',
        date: '2024-01-10',
      ),
      ArticleModel(
        id: '7',
        title: 'The Rise of New Energy Vehicle Industry',
        summary: 'With increasing environmental awareness and technological advances, new energy vehicles are gradually replacing traditional fuel vehicles, becoming the mainstream development direction of the automotive industry.',
        coverImage: 'https://pic4.zhimg.com/v2-dde84723b58e2d208690c490dc060735_720w.jpg?source=172ae18b',
        source: '汽车周刊',
        category: '汽车',
        date: '2024-01-09',
      ),
      ArticleModel(
        id: '8',
        title: 'Advantages and Practices of Cloud-Native Architecture',
        summary: 'Cloud-native architecture brings higher flexibility, scalability and reliability to enterprises, with microservices and containerization becoming mainstream choices.',
        coverImage: 'https://pic4.zhimg.com/v2-dde84723b58e2d208690c490dc060735_720w.jpg?source=172ae18b',
        source: '架构师杂志',
        category: '科技',
        date: '2024-01-08',
      ),
      ArticleModel(
        id: '9',
        title: 'Machine Learning in Medical Diagnosis',
        summary: 'Machine learning algorithms show great potential in medical image analysis, disease prediction and personalized treatment, improving diagnostic accuracy and efficiency.',
        coverImage: 'https://pic4.zhimg.com/v2-dde84723b58e2d208690c490dc060735_720w.jpg?source=172ae18b',
        source: '医疗科技',
        category: '医疗',
        date: '2024-01-07',
      ),
      ArticleModel(
        id: '10',
        title: 'The Rise and Challenges of Edge Computing',
        summary: 'Edge computing pushes data processing to the network edge, reducing latency and bandwidth requirements, providing better support for IoT and real-time applications.',
        coverImage: 'https://pic4.zhimg.com/v2-dde84723b58e2d208690c490dc060735_720w.jpg?source=172ae18b',
        source: '云计算资讯',
        category: '科技',
        date: '2024-01-06',
      ),
      ArticleModel(
        id: '11',
        title: 'New Trends in Cybersecurity Threats',
        summary: 'With the deepening of digital transformation, cybersecurity faces new challenges. Zero-trust architecture and AI-driven security solutions are becoming key to addressing threats.',
        coverImage: 'https://pic4.zhimg.com/v2-dde84723b58e2d208690c490dc060735_720w.jpg?source=172ae18b',
        source: '网络安全报',
        category: '科技',
        date: '2024-01-05',
      ),
      ArticleModel(
        id: '12',
        title: 'The Commercialization Process of Autonomous Driving Technology',
        summary: 'Autonomous driving technology is moving from laboratories to commercial applications. Level 4 autonomous driving has been achieved in specific scenarios, with fully autonomous driving on the horizon.',
        coverImage: 'https://pic4.zhimg.com/v2-dde84723b58e2d208690c490dc060735_720w.jpg?source=172ae18b',
        source: '智能汽车',
        category: '汽车',
        date: '2024-01-04',
      ),
      ArticleModel(
        id: '13',
        title: 'Sustainable Green IT Solutions',
        summary: 'Data center energy efficiency, green cloud computing and circular economy models are becoming important directions for sustainable development in the IT industry.',
        coverImage: 'https://pic4.zhimg.com/v2-dde84723b58e2d208690c490dc060735_720w.jpg?source=172ae18b',
        source: '绿色科技',
        category: '环保',
        date: '2024-01-03',
      ),
      ArticleModel(
        id: '14',
        title: 'Innovative Applications of AR/VR in Education',
        summary: 'Augmented and virtual reality technologies bring immersive experiences to education, making abstract concepts intuitive and improving learning outcomes.',
        coverImage: 'https://pic4.zhimg.com/v2-dde84723b58e2d208690c490dc060735_720w.jpg?source=172ae18b',
        source: '教育科技',
        category: '教育',
        date: '2024-01-02',
      ),
      ArticleModel(
        id: '15',
        title: 'Fintech: Reshaping the Future of Banking',
        summary: 'Digital payments, intelligent risk control and blockchain technologies are profoundly changing the operational model of traditional banking, promoting digital transformation of financial services.',
        coverImage: 'https://pic4.zhimg.com/v2-dde84723b58e2d208690c490dc060735_720w.jpg?source=172ae18b',
        source: '金融创新',
        category: '财经',
        date: '2024-01-01',
      ),
      ArticleModel(
        id: '16',
        title: 'Standardization and Interoperability of IoT Platforms',
        summary: 'To address the fragmentation of IoT devices, the industry is promoting platform standardization to achieve interconnection between devices from different manufacturers.',
        coverImage: 'https://pic4.zhimg.com/v2-dde84723b58e2d208690c490dc060735_720w.jpg?source=172ae18b',
        source: '物联网世界',
        category: '科技',
        date: '2023-12-31',
      ),
      ArticleModel(
        id: '17',
        title: 'The Evolution of Distributed Database Technology',
        summary: 'From relational databases to distributed databases, data storage technology continues to evolve, meeting the big data era\'s demands for high availability and scalability.',
        coverImage: 'https://pic4.zhimg.com/v2-dde84723b58e2d208690c490dc060735_720w.jpg?source=172ae18b',
        source: '数据库技术',
        category: '科技',
        date: '2023-12-30',
      ),
      ArticleModel(
        id: '18',
        title: 'The Booming Esports Industry',
        summary: 'Esports has evolved from entertainment to a massive industry, with accelerating professionalization and commercialization, becoming an important part of the digital economy.',
        coverImage: 'https://pic4.zhimg.com/v2-dde84723b58e2d208690c490dc060735_720w.jpg?source=172ae18b',
        source: '游戏产业',
        category: '娱乐',
        date: '2023-12-29',
      ),
      ArticleModel(
        id: '19',
        title: 'Smart Manufacturing: Core Driver of Industry 4.0',
        summary: 'Through IoT, big data and AI technologies, smart manufacturing is achieving digital, networked and intelligent transformation of production processes.',
        coverImage: 'https://pic4.zhimg.com/v2-dde84723b58e2d208690c490dc060735_720w.jpg?source=172ae18b',
        source: '工业互联网',
        category: '工业',
        date: '2023-12-28',
      ),
      ArticleModel(
        id: '20',
        title: 'Quantum Communication: Absolutely Secure Future Communication',
        summary: 'Quantum communication uses quantum mechanics principles for information transmission, theoretically providing absolutely secure communication guarantees, and has become a cutting-edge technology pursued by countries worldwide.',
        coverImage: 'https://pic4.zhimg.com/v2-dde84723b58e2d208690c490dc060735_720w.jpg?source=172ae18b',
        source: '量子科技',
        category: '军事',
        date: '2023-12-27',
      ),
    ];
  }
}